id: PAFFD6663
initial_creation_type: input
source_metadata:
  title: Shechen Rabjam Rinpoche Series
  language: bo
  description: 'Texts by and about Jigme Chökyi Senge (''jigs med chos kyi seng+ge,
    b. 1966), the seventh Rabjam Rinpoche of Shechen Monastery:'
  volume:
    e7bb1cfc56c24f51bb0ea87cf33535e2:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    fe2f26c1ab6b44d2a5d8787e2e5db2a8:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Long Life Prayers
    0e1baaa72f1943d8b95758bd088b5714:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    775608b8237c472893e63623adc20d08:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    7e4dc26149424792b5b4cf6da714f686:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Prayers
    2dc78a11d66f47979ced24c3749bc481:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    c6c02d43cd464cf190ba0ef0eec20d34:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    69306654beb94eb49f516f86fd99ad89:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:35:58.836888'
last_modified_at: '2022-03-01T01:35:58.836894'
